```mermaid
flowchart LR
    ".venv\Lib\site-packages\folium\features.py" -->|requests.get(@760| "requests.get("
    ".venv\Lib\site-packages\folium\plugins\timeline.py" -->|requests.get(@50| "requests.get("
    ".venv\Lib\site-packages\pip\_vendor\requests\__init__.py" -->|requests.get(@14| "requests.get("
    ".venv\Lib\site-packages\pip\_vendor\requests\__init__.py" -->|requests.post(@23| "requests.post("
    ".venv\Lib\site-packages\pipreqs\pipreqs.py" -->|requests.get(@184| "requests.get("
    ".venv\Lib\site-packages\requests\__init__.py" -->|requests.get(@14| "requests.get("
    ".venv\Lib\site-packages\requests\__init__.py" -->|requests.post(@23| "requests.post("
    ".venv\Lib\site-packages\tkhtmlview\html_parser.py" -->|requests.get(@540| "requests.get("
    ".venv\Lib\site-packages\yarg\parse.py" -->|requests.get(@38| "requests.get("
    "ioc\ioc_checker.py" -->|requests.get(@51| "requests.get("
    "ioc\ioc_updater.py" -->|requests.get(@10| "requests.get("
    "utils\geolocation.py" -->|requests.get(@11| "requests.get("
```