```mermaid
flowchart LR
    F1((ioc_checker.py))
    F2((ioc_updater.py))
    F3((geolocation.py))
    N4["GET@51\n<var:url>"]
    F1 --> N4
    N5["GET@10\n<var:IOC_FEED_URL>"]
    F2 --> N5
    N6["GET@11\n<var:url>"]
    F3 --> N6
```